site_name: 'Ceph Data Show'
site_url: 'https://ksingh7.github.io/data-show/'
copyright: 'Copyright Â©2018 Red Hat, Inc.'

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'images/shadowman_rgb.png'
  favicon: 'images/favicon.ico'
  static_templates:
    - 404.html
#  feature:
#    tabs: true

pages:
    - 'Getting Started': index.md
    - 'Module-1 : Ceph cluster & Object Storage Setup': Module-1.md
    - 'Module-2 : Setting up OpenShift Container Platform': Module-2.md
    - 'Module-3 : Introduction to S3A & Loading Sample Data Set': Module-3.md
    - 'Module-4 : Analytics on Metrics Data': Module-4.md
    - 'Module-5 : ML using Jupyter Datahub on Ceph': Module-5.md

extra:
  social:
    - type: 'link'
      link: 'https://www.redhat.com/en/technologies/storage/ceph'
    - type: 'twitter'
      link: 'https://twitter.com/RedHatStorage'      
    - type: 'github'
      link: 'https://github.com/ceph/ceph'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/3545/'


markdown_extensions:
    - smarty
    - toc:
        permalink: '#'
    - sane_lists
    - footnotes
    - smart_strong
    - codehilite
    - nl2br
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
